name: firetrack360
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.0.2  
  cupertino_icons: ^1.0.6
  graphql_flutter: ^5.2.0-beta.7
  shared_preferences: ^2.0.18
  flutter_svg: ^2.0.6  
  redux: ^5.0.0
  http: ^1.2.2
  flutter_redux: ^0.10.0
  dotenv: ^4.2.0
  google_fonts: ^6.2.1
  country_code_picker: ^3.1.0
  otp_text_field_v2: ^1.0.3
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3
  flutter_hooks: ^0.20.5
  jwt_decoder: ^2.0.1
  image_picker: ^1.0.7
  # intl is already included above
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  provider: ^6.1.2
  mime: ^1.0.4
  path: ^1.8.3
  permission_handler: ^11.2.0
  url_launcher: ^6.1.11
  intl: ^0.20.2
  flutter_markdown: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true 
  uses-material-design: true
    
  assets:
    - assets/images/firetrack_logo.png
    - assets/images/onboarding1.jpg
    - assets/images/onboarding2.jpg
    - assets/images/onboarding3.jpg
    - .env.development
    - .env.production
    - assets/terms/terms_en.md
    - assets/terms/terms_rw.md
    - assets/terms/terms_fr.md

  # Correct location for l10n configuration
  

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/firetrack_logo.png
  android: true
  ios: true
  web:
    generate: true
  macos: true
  linux: true

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/firetrack_logo.png"
    background_color: "#ffffff"
    theme_color: "#000000"
  macos:
    generate: true
    image_path: "assets/images/firetrack_logo.png"
  linux:
    generate: true
    image_path: "assets/images/firetrack_logo.png"
  image_path_android: "assets/images/firetrack_logo.png"  
  image_path_ios: "assets/images/firetrack_logo.png"          
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/firetrack_logo.png"
